### PR TITLE
Use the real functions + full extraction script

### PR DESCRIPTION
**Pull request by FullLifeGames**
Executing the file regularly does not work, since the relevant function execution has been commented out. This fixes that.

### CODE REVIEW

**Comment by FullLifeGames** [comment]
Added a script which extracts every file

**Comment by psthrn42** [comment]
Is this ready to merge? Thanks btw, can't believe i forgot to uncomment the functions

**Comment by FullLifeGames** [comment]
> Is this ready to merge? Thanks btw, can't believe i forgot to uncomment the functions

Will add some more decoding, but for now yeah

**Comment by FullLifeGames** [comment]
Btw @psthrn42 this kinda blew up, I tried to give you some credit as well: https://twitter.com/FullLifeGames/status/1591516840161079301

**Comment by psthrn42** [comment]
👍 also sry abt the awful code, don't actually know how to code in python really. Just thought it would be quicker to get something running

**Comment by psthrn42** [comment]
> Btw @psthrn42 this kinda blew up, I tried to give you some credit as well: https://twitter.com/FullLifeGames/status/1591516840161079301

haha that's fine

**Comment by FullLifeGames** [comment]
> 👍 also sry abt the awful code, don't actually know how to code in python really. Just thought it would be quicker to get something running

I wouldn't have figured this stuff out alone in the first place, so nice implementation regardless!

**Comment by psthrn42** [comment]
> > 👍 also sry abt the awful code, don't actually know how to code in python really. Just thought it would be quicker to get something running
> 
> I wouldn't have figured this stuff out alone in the first place, so nice implementation regardless!

It's thankfully really simple. I'm still not interpreting any of the trpfd other than the trpak names, cause i have no clue what most of the other fields do. It does contain a list of the hashes of all the files inside the trpaks, but those are also stored in the trpaks themselves so idk how that's helpful.

The next step would probably be to try and guess as many of the hashes as possible (automated obviously) so we actually know what they're called.

**Pull request merged**
